# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    qiNiuUrl: http://source.lattecake.com/

    fzcePP_url: http://apicn.faceplusplus.com/
    facePP_key: d1d4603993659cc5200fbec986f981c9
    facePP_secret: p6Cz6wELpw3lkdocklMMzhtEeGtoa4ra

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
